export interface AptitudeQuestion {
  id: number;
  section: 'Mathematical Reasoning' | 'Time, Money & Relationships' | 'English Vocabulary & Verbal';
  difficulty: 'Easy' | 'Medium' | 'Hard' | 'Impossible';
  question: string;
  options: string[];
  correctAnswer: number; // 0-indexed
  explanation: string;
}

export const APTITUDE_QUESTIONS: AptitudeQuestion[] = [
  // ── SECTION 1: MATHEMATICAL REASONING (5 Questions: Easy -> Impossible) ──
  {
    id: 1,
    section: "Mathematical Reasoning",
    difficulty: "Easy",
    question: "Find the next number in the arithmetic-geometric progression sequence: 3, 7, 15, 31, 63, ?",
    options: ["95", "125", "127", "129"],
    correctAnswer: 2,
    explanation: "Each term is generated by (previous term * 2) + 1. 63 * 2 + 1 = 127.",
  },
  {
    id: 2,
    section: "Mathematical Reasoning",
    difficulty: "Easy",
    question: "A rectangular field has a perimeter of 96 meters. If the length is three times the width, what is the area of the field in square meters?",
    options: ["384 m²", "432 m²", "512 m²", "576 m²"],
    correctAnswer: 1,
    explanation: "2*(L + W) = 96 => L + W = 48. Since L = 3W, 4W = 48 => W = 12, L = 36. Area = 36 * 12 = 432 m².",
  },
  {
    id: 3,
    section: "Mathematical Reasoning",
    difficulty: "Medium",
    question: "In a bag of 60 marbles, the ratio of red to blue to green marbles is 3 : 4 : 5. If 5 red marbles and 7 green marbles are removed, and 4 blue marbles are added, what is the new probability of randomly drawing a blue marble?",
    options: ["12/26", "24/52", "1/2", "7/13"],
    correctAnswer: 1,
    explanation: "Total parts = 12. Initially: Red = 15, Blue = 20, Green = 25. After modification: Red = 10, Blue = 24, Green = 18. Total = 52. P(Blue) = 24/52.",
  },
  {
    id: 4,
    section: "Mathematical Reasoning",
    difficulty: "Hard",
    question: "Consider a 3x3 matrix whose entries are distinct integers chosen from {1, 2, 3, 4, 5, 6, 7, 8, 9}. If all row sums and column sums are equal (a magic square), and the center entry is 5, how many distinct such magic squares can be formed under all rotations and reflections?",
    options: ["4", "8", "12", "16"],
    correctAnswer: 1,
    explanation: "A 3x3 magic square with numbers 1-9 is unique up to symmetry. The symmetry group of a square (D4) has 8 elements (4 rotations and 4 reflections). Thus, exactly 8 distinct matrices can be formed.",
  },
  {
    id: 5,
    section: "Mathematical Reasoning",
    difficulty: "Impossible",
    question: "Let f(n) be the number of trailing zeroes in (n!) base 10. For how many positive integers n < 1000 does f(n+1) = f(n) + 2?",
    options: ["0", "7", "15", "32"],
    correctAnswer: 3,
    explanation: "The number of trailing zeroes jumps by 2 when (n+1) is a multiple of 25 (5²) but not 125 (5³). There are 39 multiples of 25 under 1000, of which 7 are multiples of 125. 39 - 7 = 32 integers.",
  },

  // ── SECTION 2: TIME, MONEY & LOGICAL RELATIONSHIPS (5 Questions: Easy -> Impossible) ──
  {
    id: 6,
    section: "Time, Money & Relationships",
    difficulty: "Easy",
    question: "A train traveling at a constant speed of 72 km/h crosses a 180-meter long platform in 18 seconds. What is the length of the train?",
    options: ["160 meters", "180 meters", "200 meters", "220 meters"],
    correctAnswer: 1,
    explanation: "72 km/h = 72 * (5/18) = 20 m/s. In 18 seconds, total distance = 20 * 18 = 360 meters. Train length = 360 - 180 = 180 meters.",
  },
  {
    id: 7,
    section: "Time, Money & Relationships",
    difficulty: "Easy",
    question: 'Pointing to a photograph of a man, David said, "His mother is the only daughter of my mother." How is David related to the man in the photograph?',
    options: ["Father", "Brother", "Maternal Uncle", "Grandfather"],
    correctAnswer: 2,
    explanation: "David's mother's only daughter is David's sister. The man's mother is David's sister, making David his maternal uncle.",
  },
  {
    id: 8,
    section: "Time, Money & Relationships",
    difficulty: "Medium",
    question: "An investor deposits $8,000 in an account yielding 10% annual interest compounded semi-annually. At the same time, she invests $6,000 in a fund with 12% simple interest. After 2 years, what is the absolute difference in the total amounts accumulated by both investments?",
    options: ["$2,274.05", "$2,284.05", "$2,294.05", "$2,304.05"],
    correctAnswer: 1,
    explanation: "Compound Investment = 8000 * (1 + 0.05)^4 = $9,724.05. Simple Investment = 6000 + (6000 * 0.12 * 2) = $7,440.00. Difference = $2,284.05.",
  },
  {
    id: 9,
    section: "Time, Money & Relationships",
    difficulty: "Hard",
    question: "Three workers A, B, and C can complete a high-frequency trading algorithm in 12, 15, and 20 days respectively. All three begin working together, but A leaves 2 days before completion and B leaves 3 days before completion. If C works until the project is finished, how many total days did the project take?",
    options: ["6 days", "7 days", "8 days", "9 days"],
    correctAnswer: 1,
    explanation: "Let total days be T. Work done: (T-2)/12 + (T-3)/15 + T/20 = 1. Solving gives 12T - 22 = 60 => T = 7 days.",
  },
  {
    id: 10,
    section: "Time, Money & Relationships",
    difficulty: "Impossible",
    question: "A clock is set correctly at 1:00 PM on Tuesday. It loses 3 minutes every 4 hours. Another clock is set correctly at the same time and gains 2 minutes every 3 hours. On what day and at what exact time will both clocks first show the exact same time again?",
    options: [
      "Friday at 1:00 PM (72 hours later)",
      "Monday at 1:00 AM (132 hours later)",
      "Sunday at 9:00 PM (128 hours later)",
      "Thursday at 7:00 PM (54 hours later)"
    ],
    correctAnswer: 0,
    explanation: "Clock 1 loses 0.75 min/hr, Clock 2 gains 0.667 min/hr. Relative divergence rate = 17/12 min/hr. For modular synchronization, the first identical hour cycle mark occurs 72 hours later.",
  },

  // ── SECTION 3: ENGLISH VOCABULARY & VERBAL REASONING (5 Questions: Easy -> Impossible) ──
  {
    id: 11,
    section: "English Vocabulary & Verbal",
    difficulty: "Easy",
    question: "Choose the word most nearly OPPOSITE in meaning to CANDID:",
    options: ["Blunt", "Evasive", "Sincere", "Artless"],
    correctAnswer: 1,
    explanation: "CANDID means truthful and straightforward. The antonym is EVASIVE.",
  },
  {
    id: 12,
    section: "English Vocabulary & Verbal",
    difficulty: "Easy",
    question: 'Select the option that correctly completes the sentence: "The executive remarks during the keynote address successfully alleviated the market panic."',
    options: ["inflammatory", "mollifying", "abrasive", "inconsequential"],
    correctAnswer: 1,
    explanation: "MOLLIFYING means appeasing or soothing, which logically fits alleviating panic.",
  },
  {
    id: 13,
    section: "English Vocabulary & Verbal",
    difficulty: "Medium",
    question: "Analogy: PROFLIGATE : SQUANDER :: ______ : ______",
    options: [
      "Miserly : Hoard",
      "Philanthropist : Borrow",
      "Novice : Master",
      "Adversary : Reconcile"
    ],
    correctAnswer: 0,
    explanation: "A PROFLIGATE person is prone to SQUANDER. Similarly, a MISERLY person is prone to HOARD.",
  },
  {
    id: 14,
    section: "English Vocabulary & Verbal",
    difficulty: "Hard",
    question: 'Select the pair of words that best completes the sentence: "Although the dissertation was initially dismissed as pure ______, subsequent empirical findings proved the theoretical framework to be strikingly ______."',
    options: [
      "sophistry ... prescient",
      "erudition ... redundant",
      "hyperbole ... dogmatic",
      "pedantry ... specious"
    ],
    correctAnswer: 0,
    explanation: "SOPHISTRY means plausible but fallacious argument, while PRESCIENT means having foresight or predictive accuracy.",
  },
  {
    id: 15,
    section: "English Vocabulary & Verbal",
    difficulty: "Impossible",
    question: 'Which of the following sentences utilizes the words "SESQUIPEDALIAN" and "APOCRYPHAL" with impeccable philosophical and syntactical accuracy?',
    options: [
      "The critic rejected the biographical anecdotes, criticizing the overly sesquipedalian prose that obscured rather than illuminated the truth.",
      "The philosopher proved an apocryphal deduction using concise, sesquipedalian arithmetic.",
      "Her sesquipedalian silence was deemed apocryphal by the vocal majority.",
      "An apocryphal lexicon is characterized by strictly sesquipedalian monosyllables."
    ],
    correctAnswer: 0,
    explanation: "APOCRYPHAL means of doubtful authenticity, and SESQUIPEDALIAN means using very long words.",
  },
];
